version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book_management_app
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite

  db:
    image: mysql:8.0
    container_name: book_management_db
    environment:
      - MYSQL_DATABASE=book_management_db
      - MYSQL_ROOT_PASSWORD=2552
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: book_management_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data: